#pragma config(Sensor, dgtl2,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl12, LED,            sensorLEDtoVCC)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           gate,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           clawServo,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           temp,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int direction = 1;

int rightPower = 128;
int leftPower = 128;

void moveWheels()
{
	if(direction==1) {
		motor[rightMotor] = vexRT[Ch2];
		motor[leftMotor] = vexRT[Ch3];
	}
	else {
		motor[rightMotor] = vexRT[Ch3]*-1;
		motor[leftMotor] = vexRT[Ch2]*-1;
	}
}

bool gateOpen = true;
bool Btn6DPressed = false;

void manageGate()
{
	if(vexRT[Btn6D] == 1 && !Btn6DPressed) {
		if(gateOpen) {
			setServo(gate,127);
			waitInMilliseconds(100);
			gateOpen = false;
		}
		else {
			setServo(gate,-127);
			waitInMilliseconds(100);
			gateOpen = true;
		}
		Btn6DPressed = true;
	}
	if(vexRT[Btn6D] == 0) {
		Btn6DPressed = false;
	}
}

void openGate() {
	gateOpen = true;
	setServo(gate,-127);
}

void closeGate() {
	gateOpen = false;
	setServo(gate,127);
}

bool Btn7LPressed = false;

void reverseDirection()
{
	if(vexRT[Btn7L] == 1 && !Btn7LPressed) {
		if(direction==1)
			direction = -1;
		else
			direction = 1;
		Btn7LPressed = true;
	}
	if(vexRT[Btn7L] == 0)
		Btn7LPressed = false;
}

bool Btn5DPressed = false;
bool clawOpen = false;

void claw()
{
	if(vexRT[Btn5D] == 1 && !Btn5DPressed) {
		if(clawOpen) {
			setServo(clawServo,127);
			waitInMilliseconds(100);
			clawOpen = false;
		}
		else {
			setServo(gate,-127);
			waitInMilliseconds(100);
			clawOpen = true;
		}
		Btn5DPressed = true;
	}
	if(vexRT[Btn5D] == 0) {
		Btn5DPressed = false;
	}
}

void moveForward(int distance) {
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
	int lenc = SensorValue[leftEncoder]*-1;
	while(lenc<distance) {
		lenc = SensorValue[leftEncoder]*-1;
		motor[rightMotor] = rightPower;
		motor[leftMotor] = leftPower;
		//writeDebugStreamLine("Moving Forward a total of %d, current progress is %d",distance,enc);
	}
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}

void turnRight(int angle) {
	SensorValue[leftEncoder] = 0;
	int lenc = SensorValue[leftEncoder]*-1;
	while(lenc<angle) {
		lenc = SensorValue[leftEncoder]*-1;
		motor[rightMotor] = -1 * rightPower;
		motor[leftMotor] = leftPower;
		//writeDebugStreamLine("Turning Right a total of %d, current progress is %d",distance,enc);
	}
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}

int val = 490;
int incriment = 5;

bool Btn8LPressed = false;
void increase() {
	if(vexRT[Btn8LPressed]==1 && !Btn8LPressed) {
		val+=incriment;
		Btn8LPressed = true;
	}
	else if(Btn8LPressed && vexRT[Btn8LPressed]==0) {
		Btn8LPressed = false;
	}
}

bool Btn8RPressed = false;
void decrease() {
	if(vexRT[Btn8RPressed]==1 && !Btn8RPressed) {
		val-=incriment;
		Btn8RPressed = true;
	}
	else if(Btn8RPressed && vexRT[Btn8RPressed]==0) {
		Btn8RPressed = false;
	}
}

void auto() {
	openGate();
	moveForward(2200);
	turnRight(val);
	moveForward(2200);
	closeGate();
}

void checkAuto() {
	if(vexRT[Btn8U] == 1) {
		auto();
	}
}

task main()
{
	while(true) {
		checkAuto();

		increase();
		decrease();

		moveWheels();
		manageGate();
		reverseDirection();
		claw();
	}
}
